language: ruby
script: "bundle && bundle install && bundle exec rake test:units"
sudo: false
cache: bundler

rvm:
- 2.7
- 2.6
- 2.5

gemfile:
- gemfiles/rails5.gemfile
- gemfiles/rails6.gemfile

matrix:
  fast_finish: true

before_install:
  - gem install bundler

notifications:
  email:
    - support@travellink.com.au
